/// Flutter icons RsIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RsIcon
///      fonts:
///       - asset: fonts/RsIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class RsIcon {
  RsIcon._();

  static const _kFontFam = 'RsIcon';
  static const String? _kFontPkg = null;

  static const IconData rsicon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
